version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tests:
    image: python:3.11-alpine
    container_name: tests
    working_dir: /app
    command: ["sleep", "3600"]
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local