version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - postgres_network


  tests:
    image: python:3.11-alpine
    container_name: tests
    working_dir: /app
    command: ["sleep", "3600"]
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge